extends:
  - eslint-config-dmitmel/presets/node
  - eslint-config-dmitmel/presets/formatting
env:
  browser: true
parserOptions:
  sourceType: module

rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: functions
      allow:
        - name
        - length
        - location
        - self
        - status
        - event
        - onload

  func-names: off

  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

  node/no-unpublished-import: off

overrides:
  - files: 'tool/scripts/**/*.js'
    rules:
      node/shebang: off

  - files: 'tool/src/node-builtin-modules/**/*.js'
    rules:
      global-require: off

  - files: '**/*.ts'
    extends: eslint-config-dmitmel/presets/typescript-with-type-checking-addon

    rules:
      # because I have to use '.js' file extensions in imports
      node/no-missing-import: off

  - files:
      - 'src/**/*.ts'
    parserOptions:
      project: 'tsconfig.json'

  - files:
      - 'enhanced-ui/src/**/*.ts'
    parserOptions:
      project: 'enhanced-ui/tsconfig.json'

  - files:
      - 'tool/src/**/*.ts'
    parserOptions:
      project: 'tool/tsconfig.json'
