extends: eslint-config-dmitmel/presets/node
env:
  browser: true
parserOptions:
  sourceType: module

globals:
  ig: true
  sc: true
  nw: true
  localizeMe: true

rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: functions
      allow:
        - name
        - length
        - location
        - self
        - status
        - event

  func-names: off

  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

  node/no-unpublished-import: off

overrides:
  - files: 'tool/scripts/**/*.js'
    rules:
      node/shebang: off

  - files: 'tool/src/node-builtin-modules/**/*.js'
    rules:
      global-require: off

  - files:
      - '{,*/}src/**/*.ts'
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'

    # TODO: add TS preset to https://github.com/dmitmel/eslint-config-dmitmel
    rules:
      prefer-const: off

      # copied from camelcase
      '@typescript-eslint/camelcase':
        - warn
        - allow:
            - '^NWJS_Helpers$'

      # copied from no-unused-vars
      '@typescript-eslint/no-unused-vars':
        - warn
        - vars: all
          varsIgnorePattern: '^_'
          args: all
          argsIgnorePattern: '^_'
          ignoreRestSiblings: true
          caughtErrors: all
          caughtErrorsIgnorePattern: '^_'

      # copied from no-use-before-define
      '@typescript-eslint/no-use-before-define':
        - error
        - functions: false
          classes: false
          enums: false
          variables: true
          typedefs: false # maybe?

      # @typescript-eslint/no-useless-constructor is used instead
      no-useless-constructor: off

      # because I have to use '.js' file extensions in imports
      node/no-missing-import: off

      '@typescript-eslint/no-non-null-assertion': off

  - files:
      - 'src/**/*.ts'
    parserOptions:
      project: tsconfig.json
    globals:
      ig: off
      sc: off
    rules:
      '@typescript-eslint/no-namespace': off
      '@typescript-eslint/no-empty-interface': off
      '@typescript-eslint/unbound-method': off

  - files:
      - 'tool/src/**/*.ts'
    parserOptions:
      project: tool/tsconfig.json
