language: node_js
node_js: node

cache:
  yarn: true
  directories:
    - .eslintcache

install:
  - yarn install
  - (cd tool && yarn install)
  - yarn global add prettier
script:
  - (cd tool && yarn build:scripts && yarn build:styles)
  - eslint . --ext .js,.ts,.d.ts --ignore-path .gitignore --cache --cache-location .eslintcache/
  - prettier --check "**/*.{json,css,scss,html}"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
