language: node_js
node_js: node

cache:
  yarn: true

before_install:
  - cd tool
install:
  - yarn install
script:
  - yarn build:scripts
  - yarn build:styles
  - prettier --check "**/*.{js,ts,json,css,scss,html}"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
