language: node_js
node_js: node

cache:
  yarn: true

install:
  - yarn install
  - (cd enhanced-ui && yarn install)
  - (cd tool && yarn install)
script:
  - yarn run build
  - yarn run lint
  - yarn run prettier --check "**/*.{json,css,scss,html}"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
