language: node_js
node_js: node

cache:
  yarn: true

install:
  - yarn install
script:
  - yarn build
  - prettier --check "**/*.{js,ts,json,css,html}"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
