language: node_js
node_js: node

cache:
  yarn: true

install:
  - yarn install
  - (cd enchanced-ui && yarn install)
  - (cd tool && yarn install)
  - (cd ultimate-crosscode-typedefs && yarn install)
  - yarn global add prettier
script:
  - yarn run build
  - yarn run lint
  - prettier --check "**/*.{json,css,scss,html}"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
