name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download ultimate-crosscode-typedefs
        uses: actions/checkout@v2
        with:
          repository: dmitmel/ultimate-crosscode-typedefs
          path: ultimate-crosscode-typedefs

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Get Yarn cache directory
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
            node_modules
            ultimate-crosscode-typedefs/node_modules
          key: ${{ runner.os }}-yarn-4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-4-

      - name: Set up ultimate-crosscode-typedefs
        working-directory: ultimate-crosscode-typedefs
        run: |
          yarn install --frozen-lockfile --production
          yarn link

      - name: Install dependencies
        run: |
          yarn link ultimate-crosscode-typedefs
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build
          yarn run build:headless
          yarn run build:styles

      - name: Lint
        run: yarn run lint
      - name: Check formatting
        run: yarn run check-fmt
