name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Get Yarn cache dir
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn_cache_dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get the number of CPU threads
        id: cpu_cores
        run: echo "::set-output name=cpu_cores::$(nproc)"

      - name: Download ultimate-crosscode-typedefs
        uses: actions/checkout@v2
        with:
          repository: dmitmel/ultimate-crosscode-typedefs
          path: ultimate-crosscode-typedefs
      - name: Set up ultimate-crosscode-typedefs
        working-directory: ultimate-crosscode-typedefs
        run: |
          yarn install --production --no-lockfile
          yarn link

      - name: Install dependencies
        run: |
          export MAKEFLAGS=-j${{ steps.cpu_cores.outputs.cpu_cores }}

          yarn link ultimate-crosscode-typedefs
          yarn install --frozen-lockfile

          pushd enhanced-ui >/dev/null
          yarn install --frozen-lockfile
          popd >/dev/null

          pushd tool >/dev/null
          yarn install --frozen-lockfile
          popd >/dev/null

      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint
      - name: Check formatting
        run: yarn run check-fmt
